# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Theta_continuous <- function(Y, iter, delta, epsilon, prior_only, explore, start, progress) {
    .Call('_bggmMock_Theta_continuous', PACKAGE = 'bggmMock', Y, iter, delta, epsilon, prior_only, explore, start, progress)
}

sample_prior <- function(Y, iter, delta, epsilon, prior_only, explore, progress) {
    .Call('_bggmMock_sample_prior', PACKAGE = 'bggmMock', Y, iter, delta, epsilon, prior_only, explore, progress)
}

mv_continuous <- function(Y, X, delta, epsilon, iter, start, progress) {
    .Call('_bggmMock_mv_continuous', PACKAGE = 'bggmMock', Y, X, delta, epsilon, iter, start, progress)
}

trunc_mvn <- function(mu, rinv, z, y, cutpoints) {
    .Call('_bggmMock_trunc_mvn', PACKAGE = 'bggmMock', mu, rinv, z, y, cutpoints)
}

mv_binary <- function(Y, X, delta, epsilon, iter, beta_prior, cutpoints, start, progress) {
    .Call('_bggmMock_mv_binary', PACKAGE = 'bggmMock', Y, X, delta, epsilon, iter, beta_prior, cutpoints, start, progress)
}

Sigma_i_not_i <- function(x, index) {
    .Call('_bggmMock_Sigma_i_not_i', PACKAGE = 'bggmMock', x, index)
}

select_col <- function(x, index) {
    .Call('_bggmMock_select_col', PACKAGE = 'bggmMock', x, index)
}

select_row <- function(x, index) {
    .Call('_bggmMock_select_row', PACKAGE = 'bggmMock', x, index)
}

remove_row <- function(x, which) {
    .Call('_bggmMock_remove_row', PACKAGE = 'bggmMock', x, which)
}

remove_col <- function(x, index) {
    .Call('_bggmMock_remove_col', PACKAGE = 'bggmMock', x, index)
}

mv_ordinal_cowles <- function(Y, X, delta, epsilon, iter, MH) {
    .Call('_bggmMock_mv_ordinal_cowles', PACKAGE = 'bggmMock', Y, X, delta, epsilon, iter, MH)
}

mv_ordinal_albert <- function(Y, X, iter, delta, epsilon, K, start, progress) {
    .Call('_bggmMock_mv_ordinal_albert', PACKAGE = 'bggmMock', Y, X, iter, delta, epsilon, K, start, progress)
}

copula <- function(z0_start, levels, K, Sigma_start, iter, delta, epsilon, idx, progress) {
    .Call('_bggmMock_copula', PACKAGE = 'bggmMock', z0_start, levels, K, Sigma_start, iter, delta, epsilon, idx, progress)
}

pcor_to_cor_internal <- function(x, p) {
    .Call('_bggmMock_pcor_to_cor_internal', PACKAGE = 'bggmMock', x, p)
}

predictability_helper <- function(Y, y, XX, Xy, n, iter) {
    .Call('_bggmMock_predictability_helper', PACKAGE = 'bggmMock', Y, y, XX, Xy, n, iter)
}

beta_helper_fast <- function(XX, Xy, p, iter) {
    .Call('_bggmMock_beta_helper_fast', PACKAGE = 'bggmMock', XX, Xy, p, iter)
}

pred_helper_latent <- function(Y, XX, Xy, quantiles, n, iter) {
    .Call('_bggmMock_pred_helper_latent', PACKAGE = 'bggmMock', Y, XX, Xy, quantiles, n, iter)
}

KL_univariate <- function(var_1, var_2) {
    .Call('_bggmMock_KL_univariate', PACKAGE = 'bggmMock', var_1, var_2)
}

ppc_helper_nodewise_fast <- function(Theta, n1, n2, p) {
    .Call('_bggmMock_ppc_helper_nodewise_fast', PACKAGE = 'bggmMock', Theta, n1, n2, p)
}

KL_divergnece_mvn <- function(Theta_1, Theta_2) {
    .Call('_bggmMock_KL_divergnece_mvn', PACKAGE = 'bggmMock', Theta_1, Theta_2)
}

sum_squares <- function(Rinv_1, Rinv_2) {
    .Call('_bggmMock_sum_squares', PACKAGE = 'bggmMock', Rinv_1, Rinv_2)
}

my_dnorm <- function(x, means, sds) {
    .Call('_bggmMock_my_dnorm', PACKAGE = 'bggmMock', x, means, sds)
}

hamming_distance <- function(Rinv_1, Rinv_2, df1, df2, dens, pcors, BF_cut) {
    .Call('_bggmMock_hamming_distance', PACKAGE = 'bggmMock', Rinv_1, Rinv_2, df1, df2, dens, pcors, BF_cut)
}

correlation <- function(Rinv_1, Rinv_2) {
    .Call('_bggmMock_correlation', PACKAGE = 'bggmMock', Rinv_1, Rinv_2)
}

ppc_helper_fast <- function(Theta, n1, n2, p, BF_cut, dens, ppc_ss, ppc_cors, ppc_hd) {
    .Call('_bggmMock_ppc_helper_fast', PACKAGE = 'bggmMock', Theta, n1, n2, p, BF_cut, dens, ppc_ss, ppc_cors, ppc_hd)
}

